import{initializeApp}from"https://www.gstatic.com/firebasejs/10.0.0/firebase-app.js";
import{getAuth,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.0.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,updateDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.0.0/firebase-firestore.js";
import{SecurityMonitor}from"./security.js";

const firebaseConfig={apiKey:"AIzaSyBpJ1rZy_dsJbXmg0jPfZrVEg7vlMbwRkM",authDomain:"testhub-43fd8.firebaseapp.com",projectId:"testhub-43fd8",storageBucket:"testhub-43fd8.firebasestorage.app",messagingSenderId:"530965492161",appId:"1:530965492161:web:b8ea984ef0c9cb14763f40"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let config=null,questions=[],attempt=null,attemptId="",current=0,timerHandle=null,monitor=null,submitting=false;
const showMessage=(text,error=false)=>{$("loginMessage").textContent=text;$("loginMessage").className=`notice${error?" error":""}`};
const normalizeEmail=v=>v.trim().toLowerCase();
async function hash(value){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("");}
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const asMillis=v=>v?.toMillis?v.toMillis():v?.seconds?v.seconds*1000:typeof v==="number"?v:Date.parse(v)||0;

async function loadConfig(){try{const snap=await getDoc(doc(db,"exam_config","current_test"));if(!snap.exists())throw new Error("परीक्षा configure नहीं की गई है।");config=snap.data();const now=Date.now(),start=asMillis(config.windowStart),end=asMillis(config.windowEnd);if(config.examActive===false)throw new Error("परीक्षा अभी बंद है।");if(start&&now<start)throw new Error(`परीक्षा ${new Date(start).toLocaleString("hi-IN")} से शुरू होगी।`);if(end&&now>end)throw new Error("परीक्षा का समय समाप्त हो चुका है।");$("examInfo").textContent=`${config.examTitle||"TestHub Examination"} · ${config.durationMinutes||30} मिनट · ${config.studentLimit||10} प्रश्न`;$("startBtn").disabled=false}catch(e){$("examInfo").textContent=e.message;$("examInfo").classList.add("error")}}

onAuthStateChanged(auth,user=>{if(user)loadConfig();else signInAnonymously(auth).catch(e=>{$("examInfo").textContent="Firebase Anonymous Authentication चालू करें: "+e.message;$("examInfo").classList.add("error")})});
$("candidateForm").addEventListener("submit",async e=>{e.preventDefault();const btn=$("startBtn");btn.disabled=true;try{if(!auth.currentUser)await signInAnonymously(auth);if(!config)await loadConfig();const name=$("candidateName").value.trim(),email=normalizeEmail($("candidateEmail").value),code=$("centerCode").value.trim();if(!name||!email)throw new Error("नाम और ईमेल जरूरी है।");if(config.centerCode&&code!==String(config.centerCode))throw new Error("Exam Center Code गलत है।");attemptId=await hash(email);const ref=doc(db,"attempts",attemptId),existing=await getDoc(ref);if(existing.exists()){const data=existing.data();if(data.ownerUid!==auth.currentUser.uid)throw new Error("इस ईमेल से परीक्षा पहले ही शुरू या जमा की जा चुकी है।");if(data.status==="submitted")throw new Error("इस ईमेल से परीक्षा पहले ही जमा की जा चुकी है।");attempt=data;await loadQuestions(data.questionIds);current=Number(data.currentIndex||0);startExam(true);return}const response=await fetch("./chapter.json",{cache:"no-store"});if(!response.ok)throw new Error("Question file load नहीं हुई।");const pool=await response.json();validateQuestions(pool);questions=shuffle(pool).slice(0,Math.min(Number(config.studentLimit)||pool.length,pool.length));if(!questions.length)throw new Error("Question bank खाली है।");const startedAt=Date.now(),endsAt=startedAt+(Number(config.durationMinutes)||30)*60000;attempt={ownerUid:auth.currentUser.uid,name,email,status:"in_progress",startedAt,endsAt,currentIndex:0,questionIds:questions.map(q=>q.id),answers:{},review:[],violations:[],violationCount:0,penaltiesApplied:0,updatedAt:serverTimestamp()};await setDoc(ref,attempt);startExam(false)}catch(err){showMessage(err.message,true);btn.disabled=false}});

function validateQuestions(pool){if(!Array.isArray(pool))throw new Error("Question bank format गलत है।");for(const q of pool){if(q.id==null||!q.q||!Array.isArray(q.options)||q.options.length<2||!q.options.includes(q.a))throw new Error(`Question ${q.id??"?"} invalid है।`)}}
async function loadQuestions(ids){const response=await fetch("./chapter.json",{cache:"no-store"}),pool=await response.json();validateQuestions(pool);const map=new Map(pool.map(q=>[String(q.id),q]));questions=ids.map(id=>map.get(String(id))).filter(Boolean);if(questions.length!==ids.length)throw new Error("Saved attempt के कुछ questions उपलब्ध नहीं हैं।")}
function startExam(resumed){$("loginView").classList.add("hidden");$("examView").classList.remove("hidden");$("examTitle").textContent=config.examTitle||"TestHub Examination";$("candidateLabel").textContent=`${attempt.name} · ${attempt.email}`;render();startTimer();monitor=new SecurityMonitor({autoSubmitAfter:Number(config.autoSubmitAfter)||2,onViolation:handleViolation,onForceSubmit:()=>submitExam(true)});monitor.start();monitor.requestFullscreen();if(resumed)syncAttempt({lastResumedAt:serverTimestamp()})}
function render(){const q=questions[current];$("questionNumber").textContent=`Question ${current+1}/${questions.length}`;$("questionText").textContent=q.q;$("options").innerHTML="";q.options.forEach((option,i)=>{const label=document.createElement("label");label.className="option";const radio=document.createElement("input");radio.type="radio";radio.name="answer";radio.value=option;radio.checked=attempt.answers?.[q.id]===option;const text=document.createElement("span");text.textContent=`${String.fromCharCode(65+i)}. ${option}`;label.append(radio,text);$("options").append(label)});$("palette").innerHTML="";questions.forEach((item,i)=>{const b=document.createElement("button");b.className=`qbtn${i===current?" current":""}${attempt.answers?.[item.id]?" answered":""}${attempt.review?.includes(item.id)?" review":""}`;b.textContent=i+1;b.onclick=()=>{saveSelection();current=i;render()};$("palette").append(b)});$("prevBtn").disabled=current===0;$("securityCount").textContent=`Violations: ${attempt.violationCount||0}`;$("penaltyCount").textContent=`Penalty: ${attempt.penaltiesApplied||0}`}
function saveSelection(){const selected=document.querySelector('input[name="answer"]:checked');if(selected)attempt.answers[String(questions[current].id)]=selected.value}
async function syncAttempt(extra={}){attempt={...attempt,...extra,currentIndex:current,updatedAt:serverTimestamp()};try{await updateDoc(doc(db,"attempts",attemptId),{answers:attempt.answers,review:attempt.review,currentIndex:current,violations:attempt.violations,violationCount:attempt.violationCount,penaltiesApplied:attempt.penaltiesApplied,...extra,updatedAt:serverTimestamp()})}catch(e){console.error("Attempt sync failed",e)}}
$("prevBtn").onclick=()=>{saveSelection();current=Math.max(0,current-1);syncAttempt();render()};
$("saveNextBtn").onclick=()=>{saveSelection();if(current<questions.length-1)current++;syncAttempt();render()};
$("reviewBtn").onclick=()=>{saveSelection();const id=questions[current].id,idx=attempt.review.indexOf(id);idx>=0?attempt.review.splice(idx,1):attempt.review.push(id);syncAttempt();render()};
$("submitBtn").onclick=()=>{if(confirm("क्या आप परीक्षा final submit करना चाहते हैं?"))submitExam(false)};
async function handleViolation(event){if(submitting)return;attempt.violationCount=(attempt.violationCount||0)+1;attempt.penaltiesApplied=Number(((attempt.penaltiesApplied||0)+(Number(config.tabPenalty)||0)).toFixed(2));attempt.violations=[...(attempt.violations||[]),{type:event.type,at:Date.now()}];const original=current;for(let step=1;step<=questions.length;step++){const i=(original+step)%questions.length;if(!attempt.answers?.[questions[i].id]){current=i;break}}await syncAttempt();render()}
function startTimer(){clearInterval(timerHandle);const tick=()=>{const remaining=Math.max(0,Number(attempt.endsAt)-Date.now()),m=Math.floor(remaining/60000),s=Math.floor(remaining%60000/1000);$("timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;if(remaining<=0)submitExam(true)};tick();timerHandle=setInterval(tick,1000)}
async function submitExam(auto){if(submitting)return;submitting=true;clearInterval(timerHandle);monitor?.stop();saveSelection();let correct=0,wrong=0;for(const q of questions){const a=attempt.answers?.[q.id];if(a===q.a)correct++;else if(a)wrong++}const unanswered=questions.length-correct-wrong,raw=correct-wrong*(Number(config.negativeMarking)||0),score=Number((raw-(attempt.penaltiesApplied||0)).toFixed(2));const result={ownerUid:auth.currentUser.uid,name:attempt.name,email:attempt.email,score,total:questions.length,correct,wrong,unanswered,tabSwitches:attempt.violations.filter(v=>["tab-hidden","window-blur"].includes(v.type)).length,copiesAttempted:attempt.violations.filter(v=>["copy","cut","paste","context-menu","print","devtools"].includes(v.type)).length,penaltiesApplied:attempt.penaltiesApplied||0,violationCount:attempt.violationCount||0,violations:attempt.violations,autoSubmitted:auto,submittedAt:serverTimestamp()};try{await setDoc(doc(db,"results",attemptId),result);await updateDoc(doc(db,"attempts",attemptId),{status:"submitted",answers:attempt.answers,resultSummary:{score,correct,wrong,unanswered},submittedAt:serverTimestamp(),updatedAt:serverTimestamp()});document.fullscreenElement&&document.exitFullscreen().catch(()=>{});$("examView").classList.add("hidden");$("resultView").classList.remove("hidden");$("finalScore").textContent=`${score} / ${questions.length}`;$("finalStats").textContent=`सही: ${correct} · गलत: ${wrong} · छोड़े: ${unanswered} · सुरक्षा penalty: ${attempt.penaltiesApplied||0}`}catch(e){submitting=false;alert("Result submit नहीं हुआ। Internet जाँचकर दोबारा Submit करें।")}}
