import{initializeApp}from"https://www.gstatic.com/firebasejs/10.0.0/firebase-app.js";
import{getAuth,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.0.0/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,updateDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.0.0/firebase-firestore.js";
import{SecurityMonitor}from"./security.js";
const firebaseConfig={apiKey:"AIzaSyBp1JrZy_dsJbXmg0jPfZrVEg7vlMbwRkM",authDomain:"testhub-43fd8.firebaseapp.com",projectId:"testhub-43fd8",storageBucket:"testhub-43fd8.firebasestorage.app",messagingSenderId:"530965492161",appId:"1:530965492161:web:b8ea984ef0c9cb14763f40"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let config,questions=[],pool=[],attempt,attemptId="",current=0,timerHandle,monitor,submitting=false,pendingCandidate,rating=0;
const normalizeEmail=v=>v.trim().toLowerCase(),asMillis=v=>v?.toMillis?v.toMillis():v?.seconds?v.seconds*1000:typeof v==="number"?v:Date.parse(v)||0;
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
async function hash(v){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function message(text,error=false){$("loginMessage").textContent=text;$("loginMessage").className=`notice${error?" error":""}`}
function applyBrand(){const name=config.instituteName?.trim()||"TestHub";$("instituteName").textContent=name;document.title=`${name} | Secure Examination`;if(config.instituteLogo){$("loginLogo").src=config.instituteLogo;$("loginLogo").classList.remove("hidden");$("loginFallback").classList.add("hidden")}}
async function loadConfig(){try{const snap=await getDoc(doc(db,"exam_config","current_test"));if(!snap.exists())throw Error("परीक्षा configure नहीं की गई है।");config=snap.data();applyBrand();const now=Date.now(),start=asMillis(config.windowStart),end=asMillis(config.windowEnd);if(config.examActive===false)throw Error("परीक्षा अभी बंद है।");if(start&&now<start)throw Error(`परीक्षा ${new Date(start).toLocaleString("hi-IN")} से शुरू होगी।`);if(end&&now>end)throw Error("परीक्षा का समय समाप्त हो चुका है।");$("examInfo").textContent=`${config.examTitle||"TestHub Examination"} · ${config.durationMinutes||30} मिनट · ${config.studentLimit||10} प्रश्न`;$("continueBtn").disabled=false}catch(e){$("examInfo").textContent=e.message;$("examInfo").classList.add("error")}}
onAuthStateChanged(auth,u=>u?loadConfig():signInAnonymously(auth).catch(e=>{$("examInfo").textContent="Firebase Anonymous Authentication चालू करें: "+e.message;$("examInfo").classList.add("error")}));
$("candidateForm").onsubmit=e=>{e.preventDefault();const name=$("candidateName").value.trim(),email=normalizeEmail($("candidateEmail").value),code=$("centerCode").value.trim();if(!name||!email)return message("नाम और ईमेल जरूरी है।",true);if(config.centerCode&&code!==String(config.centerCode))return message("Exam Center Code गलत है।",true);pendingCandidate={name,email};$("configSummary").innerHTML=`<div><b>${config.durationMinutes||30}</b><br>मिनट</div><div><b>${config.studentLimit||10}</b><br>प्रश्न</div><div><b>${config.negativeMarking||0}</b><br>Negative</div><div><b>${config.maxTabSwitches||config.autoSubmitAfter||3}</b><br>Violations</div>`;$("loginView").classList.add("hidden");$("instructionsView").classList.remove("hidden")};
$("backBtn").onclick=()=>{$("instructionsView").classList.add("hidden");$("loginView").classList.remove("hidden")};$("consent").onchange=()=>$("startBtn").disabled=!$("consent").checked;$("startBtn").onclick=prepareExam;
function validate(bank){if(!Array.isArray(bank))throw Error("Question bank format गलत है।");for(const q of bank)if(q.id==null||!(q.q||q.question)||!Array.isArray(q.options)||q.options.length<2||!q.options.includes(q.a??q.answer))throw Error(`Question ${q.id??"?"} invalid है।`)}
async function getPool(){const r=await fetch("./chapter.json",{cache:"no-store"});if(!r.ok)throw Error("Question file load नहीं हुई।");pool=await r.json();validate(pool);return pool}
async function prepareExam(){const btn=$("startBtn");btn.disabled=true;try{if(!auth.currentUser)await signInAnonymously(auth);attemptId=await hash(pendingCandidate.email);const ref=doc(db,"attempts",attemptId),existing=await getDoc(ref);await getPool();if(existing.exists()){attempt=existing.data();if(attempt.ownerUid!==auth.currentUser.uid)throw Error("इस ईमेल से परीक्षा पहले ही शुरू या जमा की जा चुकी है।");if(attempt.status==="submitted")throw Error("इस ईमेल से परीक्षा पहले ही जमा की जा चुकी है।");const map=new Map(pool.map(q=>[String(q.id),q]));questions=attempt.questionIds.map(id=>map.get(String(id))).filter(Boolean);if(questions.length!==attempt.questionIds.length)throw Error("Saved questions उपलब्ध नहीं हैं।");current=Number(attempt.currentIndex||0);startExam(true);return}questions=shuffle(pool).slice(0,Math.min(Number(config.studentLimit)||pool.length,pool.length));if(!questions.length)throw Error("Question bank खाली है।");const startedAt=Date.now();attempt={ownerUid:auth.currentUser.uid,...pendingCandidate,status:"in_progress",startedAt,endsAt:startedAt+(Number(config.durationMinutes)||30)*60000,currentIndex:0,questionIds:questions.map(q=>q.id),answers:{},review:[],violations:[],violationCount:0,penaltiesApplied:0};await setDoc(ref,{...attempt,updatedAt:serverTimestamp()});startExam(false)}catch(e){message(e.message,true);$("instructionsView").classList.add("hidden");$("loginView").classList.remove("hidden");btn.disabled=false}}
function startExam(resumed){$("instructionsView").classList.add("hidden");$("examView").classList.remove("hidden");$("examTitle").textContent=config.examTitle||"TestHub Examination";$("candidateLabel").textContent=`${attempt.name} · ${attempt.email}`;render();startTimer();monitor=new SecurityMonitor({autoSubmitAfter:Number(config.maxTabSwitches||config.autoSubmitAfter)||3,onViolation:violation,onForceSubmit:()=>submitExam(true)});monitor.start();monitor.requestFullscreen();if(resumed)sync({lastResumedAt:serverTimestamp()})}
function render(){const q=questions[current],text=q.q??q.question;$("questionNumber").textContent=`Question ${current+1}/${questions.length}`;$("questionText").textContent=text;const image=q.image||q.imageUrl;$("questionImage").classList.toggle("hidden",!image);if(image)$("questionImage").src=image;$("options").innerHTML="";q.options.forEach((option,i)=>{const l=document.createElement("label"),r=document.createElement("input"),s=document.createElement("span");l.className="option";r.type="radio";r.name="answer";r.value=option;r.checked=attempt.answers?.[q.id]===option;s.textContent=`${String.fromCharCode(65+i)}. ${option}`;l.append(r,s);$("options").append(l)});$("palette").innerHTML="";questions.forEach((x,i)=>{const b=document.createElement("button");b.className=`qbtn${i===current?" current":""}${attempt.answers?.[x.id]?" answered":""}${attempt.review?.includes(x.id)?" review":""}`;b.textContent=i+1;b.onclick=()=>{save();current=i;sync();render()};$("palette").append(b)});$("prevBtn").disabled=!current;$("securityCount").textContent=`Violations: ${attempt.violationCount||0}`;$("penaltyCount").textContent=`Penalty: ${attempt.penaltiesApplied||0}`}
function save(){const s=document.querySelector('input[name="answer"]:checked');if(s)attempt.answers[String(questions[current].id)]=s.value}
async function sync(extra={}){Object.assign(attempt,extra,{currentIndex:current});try{await updateDoc(doc(db,"attempts",attemptId),{answers:attempt.answers,review:attempt.review,currentIndex:current,violations:attempt.violations,violationCount:attempt.violationCount,penaltiesApplied:attempt.penaltiesApplied,...extra,updatedAt:serverTimestamp()})}catch(e){console.error(e)}}
$("prevBtn").onclick=()=>{save();current=Math.max(0,current-1);sync();render()};$("saveNextBtn").onclick=()=>{save();current=Math.min(questions.length-1,current+1);sync();render()};$("reviewBtn").onclick=()=>{save();const id=questions[current].id,i=attempt.review.indexOf(id);i<0?attempt.review.push(id):attempt.review.splice(i,1);sync();render()};$("submitBtn").onclick=()=>confirm("Final submit करें?")&&submitExam(false);
function alertSecurity(text){$("securityAlert").textContent=text;$("securityAlert").classList.remove("hidden");setTimeout(()=>$("securityAlert").classList.add("hidden"),3500)}
async function violation(event){if(submitting)return;attempt.violationCount=(attempt.violationCount||0)+1;attempt.penaltiesApplied=Number(((attempt.penaltiesApplied||0)+(Number(config.tabPenalty)||0)).toFixed(2));attempt.violations.push({type:event.type,message:event.message||"",at:Date.now()});alertSecurity(`${event.message||"Suspicious activity"} · Violation ${attempt.violationCount}`);if(config.replaceQuestionOnSwitch!==false){const used=new Set(questions.map(q=>String(q.id))),candidate=shuffle(pool).find(q=>!used.has(String(q.id)));if(candidate){delete attempt.answers[String(questions[current].id)];questions[current]=candidate;attempt.questionIds[current]=candidate.id;await sync({questionIds:attempt.questionIds})}}await sync();render()}
function startTimer(){const tick=()=>{const left=Math.max(0,Number(attempt.endsAt)-Date.now()),m=Math.floor(left/60000),s=Math.floor(left%60000/1000);$("timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;if(!left)submitExam(true)};tick();timerHandle=setInterval(tick,1000)}
function calculate(){let correct=0,wrong=0;for(const q of questions){const a=attempt.answers?.[q.id],right=q.a??q.answer;if(a===right)correct++;else if(a)wrong++}const unanswered=questions.length-correct-wrong,score=Number((correct-wrong*(Number(config.negativeMarking)||0)-(attempt.penaltiesApplied||0)).toFixed(2));return{correct,wrong,unanswered,score}}
async function submitExam(auto){if(submitting)return;submitting=true;clearInterval(timerHandle);monitor?.stop();save();const c=calculate(),tabTypes=["tab-hidden","window-blur","fullscreen-exit","viewport-change"],copyTypes=["copy","cut","paste","context-menu","print","selection"];const result={ownerUid:auth.currentUser.uid,name:attempt.name,email:attempt.email,...c,total:questions.length,answers:attempt.answers,questionIds:attempt.questionIds,tabSwitches:attempt.violations.filter(v=>tabTypes.includes(v.type)).length,copiesAttempted:attempt.violations.filter(v=>copyTypes.includes(v.type)).length,penaltiesApplied:attempt.penaltiesApplied||0,violationCount:attempt.violationCount||0,violations:attempt.violations,autoSubmitted:auto,timeTakenSeconds:Math.round((Date.now()-attempt.startedAt)/1000),submittedAt:serverTimestamp()};try{await setDoc(doc(db,"results",attemptId),result);await updateDoc(doc(db,"attempts",attemptId),{status:"submitted",answers:attempt.answers,resultSummary:c,submittedAt:serverTimestamp(),updatedAt:serverTimestamp()});if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});showResult(result)}catch(e){submitting=false;alert("Result submit नहीं हुआ। Internet जाँचकर दोबारा Submit करें।")}}
function showResult(r){$("examView").classList.add("hidden");$("resultView").classList.remove("hidden");$("finalScore").textContent=`${r.score}/${r.total}`;$("accuracy").textContent=`${r.total?Math.round(r.correct/r.total*100):0}%`;$("correctCount").textContent=r.correct;$("wrongCount").textContent=r.wrong;$("securitySummary").textContent=`Tab/fullscreen: ${r.tabSwitches} · Copy/other: ${r.copiesAttempted} · Penalty: ${r.penaltiesApplied}`;$("reviewLedger").innerHTML="";questions.forEach((q,i)=>{const mine=attempt.answers?.[q.id]||"Not answered",right=q.a??q.answer,d=document.createElement("div");d.className=`ledger-item ${mine===right?"ok":mine==="Not answered"?"":"bad"}`;d.textContent=`Q${i+1}. ${q.q??q.question} | Your answer: ${mine} | Correct: ${right}`;$("reviewLedger").append(d)});for(let i=1;i<=5;i++){const b=document.createElement("button");b.type="button";b.className="star";b.textContent="★";b.onclick=()=>{rating=i;document.querySelectorAll(".star").forEach((x,j)=>x.classList.toggle("active",j<i))};$("stars").append(b)}}
$("feedbackBtn").onclick=async()=>{if(!rating){$("feedbackMsg").textContent="Rating required.";$("feedbackMsg").className="notice error";return}try{await updateDoc(doc(db,"results",attemptId),{rating,doubt:$("doubt").value.trim(),feedback:$("feedback").value.trim(),feedbackAt:serverTimestamp()});$("feedbackMsg").textContent="Feedback successfully saved.";$("feedbackMsg").className="notice";$("feedbackBtn").disabled=true}catch(e){$("feedbackMsg").textContent="Feedback save failed: "+e.message;$("feedbackMsg").className="notice error"}};
